title: Aditya Vighne
logo: /assets/img/my gif.gif
description: Senior Data Analyst
description:  <a href="https://www.linkedin.com/in/adityavighne/" target="_blank">LinkedIn</a>
#show_downloads: true
#google_analytics:
#theme: jekyll-theme-minimal
