title: Aditya Vighne
logo: /assets/img/my gif.gif
description: Data Analyst Portfolio
#description:  <a href="https://www.linkedin.com/in/adityavighne/" target="_blank">LinkedIn</a>
#description:  <a href="https://community.powerbi.com/t5/user/viewprofilepage/user-id/37290"target="_blank">Power BI</a>
#show_downloads: true
#google_analytics:
#theme: jekyll-theme-minimal
